In [1]:
import pandas as pd
import numpy as np

In [2]:
data_rice = pd.read_excel("/home/karthik/Cauvery Study/Crops_water_rain.xlsx",0)
X_rice = data_rice.iloc[:,[2,3]].values
y_rice = data_rice.iloc[:,[4]].values 
y_rice = y_rice.reshape(-1,1)

In [3]:
data_coffee = pd.read_excel("/home/karthik/Cauvery Study/Crops_water_rain.xlsx",1)
X_coffee = data_coffee.iloc[:,[2,3]].values
y_coffee = data_coffee.iloc[:,[4]].values 
y_coffee = y_coffee.reshape(-1,1)

In [4]:
data_pepper = pd.read_excel("/home/karthik/Cauvery Study/Crops_water_rain.xlsx",2)
X_pepper = data_pepper.iloc[:,[2,3]].values
y_pepper = data_pepper.iloc[:,[4]].values 
y_pepper = y_pepper.reshape(-1,1)

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = 0 , strategy = 'median')

In [6]:
imputer = imputer.fit(X_rice[:,:])
X_rice[:,:] = imputer.transform(X_rice[:,:])
imputer = imputer.fit(y_rice[:,:])
y_rice[:,:] = imputer.transform(y_rice[:,:])

In [7]:
imputer = imputer.fit(X_coffee[:,:])
X_coffee[:,:] = imputer.transform(X_coffee[:,:])
imputer = imputer.fit(y_coffee[:,:])
y_coffee[:,:] = imputer.transform(y_coffee[:,:])

In [8]:
imputer = imputer.fit(X_pepper[:,:])
X_pepper[:,:] = imputer.transform(X_pepper[:,:])
imputer = imputer.fit(y_pepper[:,:])
y_pepper[:,:] = imputer.transform(y_pepper[:,:])

In [9]:
import statsmodels.api as sm

In [10]:
X_rice = sm.add_constant(X_rice)
regressor_rice = sm.OLS(y_rice,X_rice).fit()

In [11]:
X_coffee = sm.add_constant(X_coffee)
regressor_coffee = sm.OLS(y_coffee,X_coffee).fit()

In [12]:
X_pepper = sm.add_constant(X_pepper)
regressor_pepper = sm.OLS(y_pepper,X_pepper).fit()

In [13]:
from ipywidgets import interactive, interact

In [14]:
def getvalues_rice(
              Groundwater_last5 = 50, 
              Rainfall_max = 100,
             ):
    
    predict_values_rice =[1,
                      Groundwater_last5,
                      Rainfall_max,
                    ]
    predict_values_rice = np.array(predict_values_rice)
    predict_values_rice = predict_values_rice.reshape(1,-1)
    y_pred_rice = regressor_rice.predict(predict_values_rice).astype(int)
    print(f"Rice for present year will be {y_pred_rice[0]} ")

In [15]:
def getvalues_coffee(
              Groundwater_last5 = 50, 
              Rainfall_max = 100,
             ):
    
    predict_values_coffee =[1,
                      Groundwater_last5,
                      Rainfall_max,
                    ]
    predict_values_coffee = np.array(predict_values_coffee)
    predict_values_coffee = predict_values_coffee.reshape(1,-1)
    y_pred_coffee = regressor_coffee.predict(predict_values_coffee).astype(int)
    print(f"Coffee for present year will be {y_pred_coffee[0]}")

In [16]:
def getvalues_pepper(
              Groundwater_last5 = 50, 
              Rainfall_max = 100,
             ):
    
    predict_values_pepper =[1,
                      Groundwater_last5,
                      Rainfall_max,
                    ]
    predict_values_pepper = np.array(predict_values_pepper)
    predict_values_pepper = predict_values_pepper.reshape(1,-1)
    y_pred_pepper = regressor_pepper.predict(predict_values_pepper).astype(int)
    print(f"Pepper for present year will be {y_pred_pepper[0]}")

In [17]:
X_int_rice = interact(getvalues_rice,
                  Groundwater_last5 = (0,160,1), 
                  Rainfall_max = (0,340,1),
             );
display(X_int_rice);
X_int_coffee = interact(getvalues_coffee,
                  Groundwater_last5 = (0,160,1), 
                  Rainfall_max = (0,340,1),
             );
display(X_int_coffee);
X_int_pepper = interact(getvalues_pepper,
                  Groundwater_last5 = (0,160,1), 
                  Rainfall_max = (0,340,1),
             );
display(X_int_pepper);

interactive(children=(IntSlider(value=50, description='Groundwater_last5', max=160), IntSlider(value=100, desc…

<function __main__.getvalues_rice(Groundwater_last5=50, Rainfall_max=100)>

interactive(children=(IntSlider(value=50, description='Groundwater_last5', max=160), IntSlider(value=100, desc…

<function __main__.getvalues_coffee(Groundwater_last5=50, Rainfall_max=100)>

interactive(children=(IntSlider(value=50, description='Groundwater_last5', max=160), IntSlider(value=100, desc…

<function __main__.getvalues_pepper(Groundwater_last5=50, Rainfall_max=100)>

In [18]:
slopes_rice = regressor_rice.params
print(slopes_rice)
slopes_coffee = regressor_coffee.params
print(slopes_coffee)
slopes_pepper = regressor_pepper.params
print(slopes_pepper)

[-27.3638158    0.16564277   0.17934667]
[33.98267842 -0.08578347 -0.05067096]
[316.47835009  -0.95291172  -0.52553428]


In [19]:
print(f"For 1 metre of groundwater depth, there will be {slopes_rice[1]} units of rice in the present year")
print(f"For 1 mm of maximum rainfall occured in 2018, there will be {slopes_rice[2]} units of rice in the present year")

For 1 metre of groundwater depth, there will be 0.16564277444943598 units of rice in the present year
For 1 mm of maximum rainfall occured in 2018, there will be 0.1793466742556733 units of rice in the present year


In [20]:
print(f"For 1 metre of groundwater depth, there will be {slopes_coffee[1]} units of coffee in the present year")
print(f"For 1 mm of maximum rainfall occured in 2018, there will be {slopes_coffee[2]} units of coffee in the present year")

For 1 metre of groundwater depth, there will be -0.08578347049010795 units of coffee in the present year
For 1 mm of maximum rainfall occured in 2018, there will be -0.05067095997314837 units of coffee in the present year


In [21]:
print(f"For 1 metre of groundwater depth, there will be {slopes_pepper[1]} units of pepper in the present year")
print(f"For 1 mm of maximum rainfall occured in 2018, there will be {slopes_pepper[2]} units of pepper in the present year")

For 1 metre of groundwater depth, there will be -0.952911715868736 units of pepper in the present year
For 1 mm of maximum rainfall occured in 2018, there will be -0.5255342807142368 units of pepper in the present year
